web:
  extends:
    file: docker-compose.yml
    service: web
  command: python app.py
  ports:
   - "5000"
  links:
   - redis:redis
  environment:
   - FOO: foo
   - BAR=bar
   - BAZ:b
   - A=a
redis:
  extends:
    file: docker-compose.yml
    service: redis
  ports:
   - "6379"